# numpy

## 安装

```shell
pip install numpy
```

## 使用

普遍的惯例是使用一个简短的别名 `np`

In [2]:
import numpy as np

## 创建数组

```python
numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)
```

* `object`：要转换成 NumPy 数组的输入对象。
* `dtype`：数据类型。若未指定，将尝试使用一个能够表示这些值的默认类型。
* `copy`：如果为 `True`，创建一个新数组。若为 `False`，尽可能使用原对象的内存。
* `order`：不常用，数组内存的布局。可选 `'K'`，`'A'`，`'C'`，`'F'`
  * `'K'`：尽量与输入保持一致。F & C 顺序保持，否则为最接近的顺序。
  * `'A'`：尽量与输入保持一致。如果输入是 F 且不是 C，则为 F 顺序，否则为 C 顺序。
  * `'C'`：按行（C语言风格）存储。
  * `'F'`：按列（Fortran风格）存储。
* `subok`：如果为 `False` 强制返回 `ndarray`。为 `True` 时，如果输入是 `ndarray` 的子类，则返回相同类型的对象。
* `ndmin`：最小维数。如果输入维度小于 `ndmin`，会补足维度。
* `like`：不常用，用于创建非 NumPy 数组。

In [5]:
np.array([1, 2, 3])

array([1, 2, 3])

```python
numpy.empty(shape, dtype=float, order='C', *, device=None, like=None)
```

创建指定形状和类型，且类型未初始化的数组。

* `shape`：数组的形状。例如 `(2, 3)` 或 `2`。
* `order`：可选 `'C'`，`'F'`。
* `device`：不常用，无需了解。

In [4]:
np.empty((2,2))

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.02359984e-306]])

```python
numpy.zeros(shape, dtype=float, order='C', *, like=None)
```

创建给定形状和类型的数组，并用 0 填充。

In [6]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])